let courseInfo = [
  {
    id: 1,
    name: "JavaScript Web Projects : 20 Projects to Build Your Portfolio",
    instructor: "Andrei Neagoie",
    topic: "javascript",
    rating: 4.8,
    price: 134.99,
    tags: "hot&new",
    img: "https://i.ibb.co/4sFKbd9/Free-Courses-to-learn-Java-Script.jpg",
  },
  {
    id: 2,
    name: "Modern Javascript : Complete Guide",
    instructor: "Brad Traversy",
    topic: "javascript",
    rating: 4.8,
    price: 159.99,
    tags: "bestseller",
    img: "https://i.ibb.co/WnRXzqn/javascriptwpseo.png",
  },
  {
    id: 3,
    name: "Learn Javascript : From zero to hero",
    instructor: "Colt Steele",
    topic: "javascript",
    rating: 4.6,
    price: 79.99,
    tags: "new",
    img: "https://i.ibb.co/mJ14sr1/0-g-Ij4mo-WHq-P1-Z1hgh.jpg",
  },
  {
    id: 4,
    name: "Modern React with Redux",
    instructor: "Andrew Mead",
    topic: "react",
    rating: 4.6,
    price: 79.99,
    tags: "new",
    img: "https://i.ibb.co/bzHBd84/f-GWjty-Qt-G4-JE7-UXga-PAN.jpg",
  },
  {
    id: 5,
    name: "React:The complete guide",
    instructor: "Maximilian Schwarzmüller",
    topic: "react",
    rating: 4.8,
    price: 139.99,
    tags: "bestseller",
    img:
      "https://i.ibb.co/Xkvp0CJ/0120-Stale-while-revalidate-Data-Fetching-with-React-Hooks-Waldek-Newsletter-5222468607946967fa1b0a4.png",
  },
  {
    id: 6,
    name: "The Complete React + Hooks Course",
    instructor: "Stephen Grinder",
    topic: "react",
    rating: 4.7,
    price: 79.99,
    tags: "bestseller",
    img: "https://i.ibb.co/bPMvkg5/react-js-image.png",
  },
  {
    id: 7,
    name: "The Complete Node.js Developer Course",
    instructor: "Andrew Mead",
    topic: "nodejs",
    rating: 4.8,
    price: 134.99,
    tags: "bestseller",
    img: "https://i.ibb.co/KLZ9szV/loopback-high-level.png",
  },
  {
    id: 8,
    name: "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
    instructor: "Maximilian Schwarzmüller",
    topic: "nodejs",
    rating: 4.6,
    price: 129.99,
    tags: "hot&new",
    img: "https://i.ibb.co/K74KyZ1/nodejs.jpg",
  },
  {
    id: 9,
    name: "MERN Stack Front To Back : Full Stack React, Redux & Node.js",
    instructor: "Brad Traversy",
    topic: "nodejs",
    rating: 4.4,
    price: 79.99,
    tags: "new",
    img: "https://i.ibb.co/T4rT28m/complete-guide-threads-nodejs.jpg",
  },
  {
    id: 10,
    name: "Python for complete beginner (with machine learning)",
    instructor: "Jose Salvatierra",
    topic: "python",
    rating: 4.8,
    price: 99.99,
    tags: "bestseller",
    img: "https://i.ibb.co/Z1ymfmv/1-b-O6l-Rw-KN8-Tl-Ph-Ebx-NTHh-AA.png",
  },
  {
    id: 11,
    name: "The Python 3 Bootcamp",
    instructor: "Colt Steele",
    topic: "python",
    rating: 4.6,
    price: 129.99,
    tags: "bestseller",
    img: "https://i.ibb.co/z8KDg2g/How-to-Learn-Python.jpg",
  },
  {
    id: 12,
    name: "Python:A beginner's guide",
    instructor: "Dr. Chuck",
    topic: "python",
    rating: 4.9,
    price: 129.99,
    tags: "hot&new",
    img: "https://i.ibb.co/NnWR4FZ/2271214-c9ab-2.jpg",
  },
];

export default courseInfo;
